### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by biafra** [mig0/Games-Checkers#1]
Trying to perl Makefile.PL it stops with

/home/$USER/Downloads/Games-Checkers-0.2.0/data/games/russian/default.pdn is encountered a second time at /usr/share/perl/5.22/File/Find.pm line 79.

Using perl 5.22 

It's because data/games/default is a link ?

**Comment by mig0** [comment]
There was a regression in ExtUtils::MakeMaker, see discussion in
https://github.com/Perl-Toolchain-Gang/ExtUtils-Manifest/issues/5

They suggested the bug is in File::Find and nobody wants to fix the situation...

I will address this in Games-Checkers 0.2.1.

**Comment by mig0** [comment]
Fixed in 0.3.0.

commit https://github.com/mig0/Games-Checkers/commit/4e50693504f50a275bf9501b3c094e370b5245d5
